version: "3"

services:
  frontend:
    build:
      context: frontend
    ports:
      - "0.0.0.0:3000:3000"
    command:
      - npm run serve --host "0.0.0.0:3000"

  backend:
    build:
      context: backend
    environment:
      PYTHONUNBUFFERED: "1"
    ports:
      - "0.0.0.0:8000:8000"

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - frontend
      - backend
    links:
      - frontend
      - backend

